---
title: "Results"
author: "Joe Hilgard"
date: "March 20, 2016"
output: word_document
---

``` {r setup, include = F}
source("2_analysis.R")

reportCI = function(smd = d, n.1 = n.1, n.2 = n.2) {
  output = ci.smd(smd = d, n.1 = n.1, n.2 = n.2)
  paste0("*d* = ", signif(output$smd, 2), 
         ", [", signif(output$Lower.Conf.Limit.smd, 2),
         ", ", signif(output$Upper.Conf.Limit.smd, 2),
         "]")
}
```

## Manipulation Check
Participant ratings on the post-questionnaires were submitted to 2 (Violence) x 2 (Difficulty) ANOVA. The manipulation was highly effective: participants indicated that the violent game (M = `r vioMeans[2] %>% signif(2)`; SD = `r vioSDs[2] %>% signif(2)`) was much more violent than the nonviolent game (M = `r vioMeans[1] %>% signif(2)`, SD = `r vioSDs[1] %>% signif(2)`; d = `r reportCI(smd = (vioMeans[2] - vioMeans[1]) / pool.sd(vioSDs, vioN), n.1 = vioN[1], n.2 = vioN[2]))`. 

Mean evaluations of the participants’ interactions with the partner were also assessed. Participants generally indicated that they were irritated (M = 4.92, SD = 1.71), angered (M = 4.22, SD = 1.75), and annoyed (M = 4.92, SD = 1.80) by their partner. Furthermore, they were not happy (M = 2.45, SD = 1.41) or pleased (M = 2.18, SD = 1.37) with their partner and found the feedback unhelpful (M = 1.78, SD = 1.23).

To determine whether the coldpressor dependent variable was a sensitive measure of aggression, I tested whether these participant evaluations were related to coldpressor assignments. First, a principal component was extracted from participants’ six ratings of the interaction, described above. The first component accounted for 57% of the variance and had the expected pattern of loadings: .51, .45, and .50 for irritation, anger, and annoyance, -.35, -.22, and -.33 for happiness, helpfulness, and pleasure. This component, hereafter referred to as composite irritation, was then used as a linear predictor of coldpressor assignment. The relationship was moderately strong, t(196) = 5.43, r = .36 (.22, .46), suggesting that the coldpressor measure was indeed influenced by participants’ intent to aggress. A scatterplot and loess regression line are provided in Figure 1.

A 2 (Violence) x 2 (Difficulty) ANOVA was conducted to determine whether the game played influenced participants’ ratings of the interaction. Effects were small and not statistically significant, suggesting that the game played had a minimal influence on participants’ composite irritation. See Table 1 for this ANOVA output.

## Primary Outcome 
Coldpressor assignments were found to be non-normally distributed. Distributions appeared to resemble a mixture of a uniform and a point such that participants either followed directions and assigned a random value between 1 and 9 or they decided to aggress against their partner and assigned a 9. See histograms in Figure 2 and means and SDs in Table 2.

Because of this non-normal distribution, I attempted to model the data in several ways. First, I treated the data as normally distributed for a typical ANOVA, generating effect sizes, confidence intervals, and Bayes factors. Next, I treated the data as being censored from above, attempting to model possible coldpressor assignments above the maximum. Finally, I treated coldpressor assignment as a categorical outcome with 1-8 representing a single nonaggressive response category and 9 representing an aggressive response category. This categorized variable was analyzed with logistic regression. 

###Conventional General Linear Models.
General linear models were used to look for main effects and interactions of game difficulty, game violence, and 2D:4D ratio. Two models were used to look for effects of left and right 2D:4D ratio, separately. Factors were contrast-coded and 2D:4D ratios were centered to preserve orthogonality of parameter estimates.

[TESTS GO HERE]

Because the earlier manipulation and sensitivity check indicated that much of the variance in aggression could be predicted by composite irritation and that composite irritation was largely orthogonal to the experimental manipulation, composite irritation was added as a covariate. However, this did not increase the observed effect size. In the 2x2 ANOVA, effects of Violence, Difficulty, and their interaction were small: t(193)s = 1.40, 1.81, and -1.62; rs = .09 (-.04, .24), .13 (-.01, .26), and -.11 (-.25 .03), respectively. When the interaction term was dropped, main effects again shrank (Violence: t(194) = 0.36, r = .03 (-.11, .16); Difficulty: t(194) = 0.93, r = .07 (-.07, .20)).

###Bayesian ANOVA. 
Models were compared using the BayesFactor package for R (Morey & Rouder, 2014). The scale of the effect size under the alternative hypothesis was specified as  d~Cauchy(.4). Models were generated to represent all possible combinations of main effects and/or interactions. Models including interactions were constrained to also include lower-order interactions and main effects. All models were compared to a null-hypothesis model including no effects. Bayes factors involving 2D:4D were similar regardless of whether the right or left hand was used; to be conservative, I report the Bayes factor closer to 1.

Of all the models, the null-hypothesis model was best supported by the data. Models of main effects of Violence, Difficulty, or 2D:4D were each outperformed by the null model (Bayes factors = 4.51, 3.87, and 5.64 in favor of the null, respectively). Models containing interactions were further outperformed by the null. The full model of 2 (Violence) x 2 (Difficulty) x 2D:4D was not preferred to the null (Bayes factor = 558). The 2 (Violence) x 2 (Difficulty) model was similarly outperformed by the null (Bayes factor = 8.69). Thus, the null model was supported over the hypothesized effect of each predictor.

When composite irritation was added as a predictor, Bayes factor strongly favored the composite-irritation-model to the null model, B = 73,980. This model was also preferred to models adding effects of violence (B = 5.01), difficulty (B = 3.55), additive effects of violence and difficulty (B = 17.93), or interactive effects of violence and difficulty (B = 22.72). This indicates that variance in coldpressor duration could be predicted by composite irritation but not by game condition.

###Censored regression. 
To attempt to ameliorate the potential ceiling effect, a censored regression model was fit with the ‘censReg’ package for R (Henningsen, 2013). This fits a censored-regression Tobit model and attempts to model values that exceed the maximum of the scale.

Again, the 2 (Violence) x 2 (Difficulty) model was fit. As in the conventional ANOVA, a small and negative interaction was found (t(219) = -2.26, r = -.15 (-.27, -.02)) such that violent content increased aggressive behavior in the easy condition (t(110) = 1.95, r = .18 (-.01, .36)) but decreased aggressive behavior in the difficult condition (t(111) = -1.32, r = -.12 (-.30, .06)). Main effects of Violence and Difficulty were small, t(219) = 1.84, r = .12 (-.01, .25) and t(219) = 2.41, r = .16 (.03, .28), respectively.

As before, this interaction seems uninterpretable in light of the theoretical predictions.  Removing this interaction from the model again dramatically reduced the size of the estimated main effects. Effects of Violence and Difficulty were very close to zero, t(223) = 0.34, r = .02 (-.11, .15) and t(220) = 1.15, r = .07 (-.05, .21), respectively.

Main effects of 2D:4D were again approximately zero, t(151) = -0.19, r = -.02 (-.17, .14) and t(151) = 0.13, r = .01 (-.15, .17) for left- and right-hand 2D:4D, respectively. Higher-order interactions with Violence or Difficulty were not supported (all |t| < 1.5).  

###Logistic regression. 
Another possibility is that participants completed the coldpressor assignment in one of two ways: either they followed instructions and randomly assigned the other participant to a value between 1 and 9, or they decided to aggress and assign the other participant the maximum value. To model this possibility, I treated the response variable as a dichotomous outcome. Participants assigning values 1-8 were treated as one category (nonaggressive response) and participants assigning value 9 were treated as the other (aggressive response). Logistic regression was performed to test whether the odds of aggressing were influenced by the experimental assignment.

Analysis began with a 2 (Violence) x 2 (Difficulty) general linear model with a logit link function. A small negative interaction was again observed, although it was not statistically significant (t(219) = -1.60, r = -.11 (-.23, .03). Here, the nature of this interaction was such that Violence decreased aggression when the game was easy, t(103) = -0.63, r = -.06 (-.25, .13) and decreased it to a lesser extent when the game was hard, t(106) = -.284, r = -.03 (-.22, .16). The main effect of Violence was quite small, t(219) = 0.72, r = .05 (-.08, .18), although participants were slightly more likely to aggress in the Difficult condition, t(219) = 2.21, r = .15 (.01, .27).

Again, because the negative interaction is difficult to interpret given the relevant theory, it was dropped from the model and main effects again estimated. Violence did not appear to influence aggression, t(220) = -0.70, r = -.05 (-.18, .08). Difficulty also had a minimal effect on aggression, t(220) = 1.58, r = .11 (-.03, .23).	Application of composite irritation as a covariate to these models revealed an effect of composite irritation, t(196) = 4.19, r = .29 (.15, .40), but did not increase the estimated effects of violence, difficulty, or their interaction.

Main effects of 2D:4D on aggression were again negligible. Left 2D:4D did not predict aggression, t(151) = -0.15, r = -.01 (-.17, .15), nor did right 2D:4D, t(150) = -0.05, r = -.05 (-.21, .11). Application of composite irritation as a covariate did not influence the estimated effect. Higher-order interactions of 2D:4D with factors of Violence or Difficulty were not supported by the results (all |t| < 1.53).

###Non-local Bayesian prior. 
In the Bayesian hypothesis tests provided above, we use a non-directional, non-specific alternative hypothesis scaled roughly to the magnitude of the expected effect. While this is a useful hypothesis to test, it would also be useful to compare the obtained results against a more specific alternative hypothesis representing the effect as estimated from previous meta-analysis, δ = .43 (.35, .52) (Anderson et al., 2010).

The main effect of Violence in the traditional ANOVA, omitting the Violence x Difficulty interaction, was d = 0.09 (-0.17, 0.35). An online Bayes factor calculator (Dienes, 2008) was used to compare the evidence for H0: δ = 0 relative to H1: δ = .43 (.35, .52). The obtained Bayes factor substantially preferred the null, B01 = 17.7.
